export const LOAD_EMPLOYEES_START="LOAD_EMPLOYEES_START"
export const LOAD_EMPLOYEES_SUCCESS="LOAD_EMPLOYEES_SUCCESS"
export const LOAD_EMPLOYEES_ERROR="LOAD_EMPLOYEES_ERROR"

export const CREATE_EMPLOYEE_START="CREATE_EMPLOYEE_START"
export const CREATE_EMPLOYEE_SUCCESS="CREATE_EMPLOYEE_SUCCESS"
export const CREATE_EMPLOYEE_ERROR="CREATE_EMPLOYEE_ERROR"


export const DELETE_EMPLOYEE_START="DELETE_EMPLOYEE_START"
export const DELETE_EMPLOYEE_SUCCESS="DELETE_EMPLOYEE_SUCCESS"
export const DELETE_EMPLOYEE_ERROR="DELETE_EMPLOYEE_ERROR"



export const EDIT_EMPLOYEE_START="EDIT_EMPLOYEE_START"
export const EDIT_EMPLOYEE_SUCCESS="EDIT_EMPLOYEE_SUCCESS"
export const EDIT_EMPLOYEE_ERROR="EDIT_EMPLOYEE_ERROR"
